version: '3.9'

services:

  users_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    volumes:
      - users_data:/var/lib/postgresql/data
      - ./init_db/init_users.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth_net
      - database_net


  trading_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading_db
    volumes:
      - trading_data:/var/lib/postgresql/data
      - ./init_db/init_trading.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database_net


  auth_service:
    build: ./auth_service
    image: trader_idp_auth_service
    container_name: trader_idp_auth_service
    ports:
      - "8000:8000"
    environment:
      - USERS_DB_URL=postgresql://postgres:postgres@users_db:5432/users_db
      - JWT_SECRET=supersecret
    depends_on:
      - users_db
    networks:
      - auth_net

  db_service:
    build: ./db_service
    image: trader_idp_db_service
    container_name: trader_idp_db_service
    ports:
      - "8001:8001"
    environment:
      - USERS_DB_URL=postgresql://postgres:postgres@users_db:5432/users_db
      - TRADING_DB_URL=postgresql://postgres:postgres@trading_db:5432/trading_db
      - JWT_SECRET=supersecret
    depends_on:
      - trading_db
      - users_db
    networks:
      - database_net

  business_logic_service:
    build: ./business_logic_service
    image: trader_idp_business_logic_service
    container_name: trader_idp_business_logic_service
    environment:
      - USERS_DB_URL=postgresql://postgres:postgres@users_db:5432/users_db
      - TRADING_DB_URL=postgresql://postgres:postgres@trading_db:5432/trading_db
    depends_on:
      - trading_db
    networks:
      - database_net

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - database_net

volumes:
  users_data:
  trading_data:

networks:
  auth_net:
  database_net:
