version: '3.9'

services:

  db_service:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_db
    volumes:
      - main_data:/var/lib/postgresql/data
      - ./init_main_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth_net
      - db_interaction_net
      - business_logic_net
      - adminer_net


  auth_service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    image: trader_idp_auth_service
    container_name: trader_idp_auth_service
    ports:
      - "8000:8000"
    environment:
      - MAIN_DB_URL=postgresql://postgres:postgres@db_service:5432/main_db
      - JWT_SECRET=supersecret
    depends_on:
      - db_service
    networks:
      - auth_net


  db_interaction_service:
    build:
      context: .
      dockerfile: ./db_interaction_service/Dockerfile
    image: trader_idp_db_interaction_service
    container_name: trader_idp_db_interaction_service
    ports:
      - "8001:8001"
    environment:
      - MAIN_DB_URL=postgresql://postgres:postgres@db_service:5432/main_db
      - JWT_SECRET=supersecret
    depends_on:
      - db_service
    networks:
      - db_interaction_net

  business_logic_service:
    build:
      context: .
      dockerfile: ./business_logic_service/Dockerfile
    image: trader_idp_business_logic_service
    container_name: trader_idp_business_logic_service
    environment:
      - MAIN_DB_URL=postgresql://postgres:postgres@db_service:5432/main_db
    depends_on:
      - db_service
      - db_interaction_service
      - auth_service
    networks:
      - business_logic_net

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - adminer_net

  finance_service:
    build:
      context: .
      dockerfile: ./finance_service/Dockerfile
    image: trader_idp_finance_service
    container_name: trader_idp_finance_service
    ports:
      - "8002:8002"
    networks:
      - finance_net

volumes:
  main_data:

networks:
  auth_net:
  db_interaction_net:
  business_logic_net:
  adminer_net:
  finance_net:
