
services:

  kong:
    image: kong:3.6
    container_name: trader_idp_kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"  # Proxy port
      - "8443:8443"  # SSL proxy port
      - "8001:8001"  # Admin API port
      - "8444:8444"  # SSL Admin API port
    networks:
      - kong_net
      - auth_net
      - db_interaction_net
      - finance_net
    depends_on:
      - auth_service
      - db_interaction_service
      - finance_service

  db_service:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_db
    volumes:
      - main_data:/var/lib/postgresql/data
      - ./init_main_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth_net
      - db_interaction_net
      - business_logic_net
      - adminer_net


  auth_service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    image: trader_idp_auth_service
    container_name: trader_idp_auth_service
    ports:
      - "8002:8002"
    environment:
      - MAIN_DB_URL=postgresql://postgres:postgres@db_service:5432/main_db
      - JWT_SECRET=supersecret
      - JWT_ALGORITHM=HS256
    depends_on:
      - db_service
    networks:
      - auth_net


  db_interaction_service:
    build:
      context: .
      dockerfile: ./db_interaction_service/Dockerfile
    image: trader_idp_db_interaction_service
    container_name: trader_idp_db_interaction_service
    ports:
      - "8003:8003"
    environment:
      - MAIN_DB_URL=postgresql://postgres:postgres@db_service:5432/main_db
      - JWT_SECRET=supersecret
      - JWT_ALGORITHM=HS256
    depends_on:
      - db_service
    networks:
      - db_interaction_net

  business_logic_service:
    build:
      context: .
      dockerfile: ./business_logic_service/Dockerfile
    image: trader_idp_business_logic_service
    container_name: trader_idp_business_logic_service
    environment:
      - MAIN_DB_URL=postgresql://postgres:postgres@db_service:5432/main_db
    depends_on:
      - db_service
      - db_interaction_service
      - auth_service
    networks:
      - business_logic_net

  adminer:
    image: adminer
    container_name: trader_idp_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - adminer_net

  finance_service:
    build:
      context: .
      dockerfile: ./finance_service/Dockerfile
    image: trader_idp_finance_service
    container_name: trader_idp_finance_service
    ports:
      - "8004:8004"
    networks:
      - finance_net

volumes:
  main_data:

networks:
  auth_net:
  db_interaction_net:
  business_logic_net:
  adminer_net:
  finance_net:
  kong_net:
